------------------------------------------TRIGGERS------------------------------------------
CREATE OR REPLACE TRIGGER TGR_CREAR_EXPEDIENTE
    AFTER INSERT ON DATOS_PERSONALES 
    FOR EACH ROW
    BEGIN
        INSERT INTO ANTECEDENTES_DE_EVALUACION_CLINICA (PACIENTE_ID) VALUES (:NEW.PACIENTE_ID);
        INSERT INTO MEDICAMENTOS_DE_CONSUMO_ACTUAL (PACIENTE_ID) VALUES (:NEW.PACIENTE_ID);
        INSERT INTO DATOS_ANTROPOMETRICOS (PACIENTE_ID) VALUES (:NEW.PACIENTE_ID);
        INSERT INTO HABITOS (PACIENTE_ID) VALUES (:NEW.PACIENTE_ID);
        INSERT INTO FRECUENCIA_CONSUMO (PACIENTE_ID) VALUES (:NEW.PACIENTE_ID);
END;
--Preguntar por mas ideas de triggers

------------------------------------------AUDITORIAS----------------------------------------

CREATE TABLE AUDITORIA_GENERAL(
    ID_AUDITORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO VARCHAR2(100) NOT NULL,
    ACCION VARCHAR2(100) NOT NULL,
    TABLA VARCHAR2(100) NOT NULL,
    FECHA DATE NOT NULL
    );
    
-----------------------------------AUDITORIA-DATOS-PERSONALES-------------------------------

--Datos Personales
CREATE OR REPLACE TRIGGER AUDITAR_DATOS_PERSONALES_INSERT
    AFTER INSERT ON DATOS_PERSONALES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'DATOS PERSONALES', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_DATOS_PERSONALES_UPDATE
    AFTER UPDATE ON DATOS_PERSONALES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'DATOS PERSONALES', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_DATOS_PERSONALES_DELETE
    AFTER DELETE ON DATOS_PERSONALES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'DATOS PERSONALES', SYSDATE);
    END;

-------------------------------------AUDITORIA-ANTECEDENTES--------------------------------

--Patologia Familiar
CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_FAMILIAR_INSERT
    AFTER INSERT ON PATOLOGIA_FAMILIAR
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'PATOLOGIA FAMILIAR', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_FAMILIAR_UPDATE
    AFTER UPDATE ON PATOLOGIA_FAMILIAR
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'PATOLOGIA FAMILIAR', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_FAMILIAR_DELETE
    AFTER DELETE ON PATOLOGIA_FAMILIAR
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'PATOLOGIA FAMILIAR', SYSDATE);
    END;

--Patologia Personal
CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_PERSONAL_INSERT
    AFTER INSERT ON PATOLOGIA_PERSONAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'PATOLOGIA PERSONAL', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_PERSONAL_UPDATE
    AFTER UPDATE ON PATOLOGIA_PERSONAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'PATOLOGIA PERSONAL', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_PATOLOGIA_PERSONAL_DELETE
    AFTER DELETE ON PATOLOGIA_PERSONAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'PATOLOGIA PERSONAL', SYSDATE);
    END;

-------------------------------------AUDITORIA-MEDICAMENTOS--------------------------------

--Medicamentos
CREATE OR REPLACE TRIGGER AUDITAR_MEDICAMENTO_INSERT
    AFTER INSERT ON MEDICAMENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'MEDICAMENTO', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_MEDICAMENTO_UPDATE
    AFTER UPDATE ON MEDICAMENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'MEDICAMENTO', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_MEDICAMENTO_DELETE
    AFTER DELETE ON MEDICAMENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'MEDICAMENTO', SYSDATE);
    END;

---------------------------------AUDITORIA-DATOS-ANTROPOMETRICOS---------------------------

--Mediciones
CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_INSERT
    AFTER INSERT ON MEDICIONES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'MEDICIONES', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_UPDATE
    AFTER UPDATE ON MEDICIONES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'MEDICIONES', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_DELETE
    AFTER DELETE ON MEDICIONES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'MEDICIONES', SYSDATE);
    END;

--Mediciones de seguimiento
CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_DE_SEGUIMIENTO_INSERT
    AFTER INSERT ON MEDICIONES_DE_SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'MEDICIONES DE SEGUIMIENTO', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_DE_SEGUIMIENTO_UPDATE
    AFTER UPDATE ON MEDICIONES_DE_SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'MEDICIONES DE SEGUIMIENTO', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_MEDICIONES_DE_SEGUIMIENTO_DELETE
    AFTER DELETE ON MEDICIONES_DE_SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'MEDICIONES DE SEGUIMIENTO', SYSDATE);
    END;

--Bioimpedancia
CREATE OR REPLACE TRIGGER AUDITAR_BIOIMPEDANCIA_INSERT
    AFTER INSERT ON BIOIMPEDANCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'BIOIMPEDANCIA', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_BIOIMPEDANCIA_UPDATE
    AFTER UPDATE ON BIOIMPEDANCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'BIOIMPEDANCIA', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_BIOIMPEDANCIA_DELETE
    AFTER DELETE ON BIOIMPEDANCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'BIOIMPEDANCIA', SYSDATE);
    END;

-------------------------------------AUDITORIA-HABITOS--------------------------------------

--Actividades
CREATE OR REPLACE TRIGGER AUDITAR_ACTIVIDADES_INSERT
    AFTER INSERT ON ACTIVIDADES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'ACTIVIDADES', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_ACTIVIDADES_UPDATE
    AFTER UPDATE ON ACTIVIDADES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'ACTIVIDADES', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_ACTIVIDADES_DELETE
    AFTER DELETE ON ACTIVIDADES
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'ACTIVIDADES', SYSDATE);
    END;

--Alimentos
CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_INSERT
    AFTER INSERT ON ALIMENTOS
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'ALIMENTOS', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_UPDATE
    AFTER UPDATE ON ALIMENTOS
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'ALIMENTOS', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_DELETE
    AFTER DELETE ON ALIMENTOS
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'ALIMENTOS', SYSDATE);
    END;
    
--Consumo Usual
CREATE OR REPLACE TRIGGER AUDITAR_CONSUMO_USUAL_INSERT
    AFTER INSERT ON CONSUMO_USUAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'CONSUMO USUAL', SYSDATE);
    END;

CREATE OR REPLACE TRIGGER AUDITAR_CONSUMO_USUAL_UPDATE
    AFTER UPDATE ON CONSUMO_USUAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'CONSUMO USUAL', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_CONSUMO_USUAL_DELETE
    AFTER DELETE ON CONSUMO_USUAL
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'CONSUMO USUAL', SYSDATE);
    END;

------------------------------AUDITORIA-FRECUNCIA-DE-CONSUMO------------------------------

--Alimentos Frecuencia
CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_FRECUENCIA_INSERT
    AFTER INSERT ON ALIMENTOS_FRECUENCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'ALIMENTOS FRECUENCIA', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_FRECUENCIA_UPDATE
    AFTER UPDATE ON ALIMENTOS_FRECUENCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'ALIMENTOS FRECUENCIA', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_ALIMENTOS_FRECUENCIA_DELETE
    AFTER DELETE ON ALIMENTOS_FRECUENCIA
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'ALIMENTOS FRECUENCIA', SYSDATE);
    END;

----------------------------------AUDITORIA-SEGUIMIENTO-----------------------------------

--Seguimiento
CREATE OR REPLACE TRIGGER AUDITAR_SEGUIMIENTO_INSERT
    AFTER INSERT ON SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'INSERT', 'SEGUIMIENTO', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_SEGUIMIENTO_UPDATE
    AFTER UPDATE ON SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'UPDATE', 'SEGUIMIENTO', SYSDATE);
    END;
    
CREATE OR REPLACE TRIGGER AUDITAR_SEGUIMIENTO_DELETE
    AFTER DELETE ON SEGUIMIENTO
    FOR EACH ROW
    BEGIN
    INSERT INTO AUDITORIA_GENERAL (USUARIO, ACCION, TABLA, FECHA) 
    VALUES (USER, 'DELETE', 'SEGUIMIENTO', SYSDATE);
    END;









