
--Inserts a la tabla de referencia dt_sexo
INSERT INTO DT_SEXO(TIPO)VALUES('Femenina');
INSERT INTO DT_SEXO(TIPO)VALUES('Masculino');
INSERT INTO DT_SEXO(TIPO)VALUES('Otro');
INSERT INTO DT_SEXO(TIPO)VALUES('No respondo');

--Inserts a la tabla de referencia dt_estado_civil

INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Casado');
INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Soltero');
INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Divorciado');
INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Viudo');
INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Union Libre');
INSERT INTO DT_ESTADO_CIVIL(TIPO)VALUES('Otro');

--Inserts a la tabla de referencia nacionalidad

INSERT INTO DT_NACIONALIDAD(TIPO)VALUES('Costarricense');
INSERT INTO DT_NACIONALIDAD(TIPO)VALUES('Extranjero');

--Inserts a la tabla de referencia provincia

INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('San Jose');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Alajuela');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Cartago');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Heredia');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Guanacaste');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Puntarenas');
INSERT INTO DT_PROVINCIA(NOMBRE)VALUES('Limon');

--Inserts a la tabla de referencia canton
--Cantonces de la provincia de San Jose
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'San Jose');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Escazu');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Desamparados');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Puriscal');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Tarrazu');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Aserri');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Mora');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Goicoechea');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Santa Ana');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Alajuelita');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Vasquez de Coronado');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Acosta');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Tibas');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Moravia');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Montes de Oca');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Turrubares');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Dota');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Curridabat');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Perez Zeledon');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(1,'Leon Corte Castro');

--Cantonces de la provincia de Alajuela
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Alajuela');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'San Ramon');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Grecia');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'San Mateo');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Atenas');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Naranjo');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Palmares');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Poas');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Orotina');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'San Carlos');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Zarcero');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Sarchi');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Upala');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Los Chiles');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Guatuso');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(2,'Rio Cuarto');

--Cantonces de la provincia de Cartago
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Cartago');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Paraiso');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'la Union');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Jimenez');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Turrialba');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Alvarado');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'Oreamuno');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(3,'El Guarco');

--Cantones de la provincia de Heredia
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Heredia');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Barva');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Santo Domingo');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Santa Barbara');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'San Rafael');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'San Isidro');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Belen');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Flores');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'San Pablo');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(4,'Sarapiqui');

--Cantones de la provincia de Guanacaste
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Liberia');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Nicoya');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Santa Cruz');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Bagaces');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Carrillo');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Cañas');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Abangares');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Tilaran');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Nandayure');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'La Cruz');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(5,'Hojancha');

--Cantones de la provincia de Puntarenas
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Puntarenas');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Esparza');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Buenos Aires');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Montes de Oro');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Osa');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Quepos');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Golfito');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Coto Brus');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Parrita');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Corredores');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(6,'Garabito');

--Cantones de la provincia de Limon
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Limon');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Pococi');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Siquirres');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Talamanca');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Matina');
INSERT INTO DT_CANTON(PROVINCIA_ID, NOMBRE)VALUES(7,'Guacimo');

--Inserts a la tabla de referencia distrito
--Distritos del canton de San Jose de la provincia San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Carmen');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Merced');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Hospital');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Catedral');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Zapote');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'San Francisco de Dos Rios');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Uruca');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Mata Redonda');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Pavas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'Hatillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(1,'San Sebastian');

--Distritos del canton de Escazu de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(2,'Escazu');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(2,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(2,'San Rafael');

--Distritos del canton de Desamparados de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Desamparados');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Miguel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Juan de Dios');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Rafael Arriba');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Frailes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Patarra');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Cristobal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Rosario');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'damas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'San Rafael Abajo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Gravilias');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(3,'Los Guido');

--Distritos del canton de Purriscal de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Santiago');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Mercedes Sur');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Barbacoas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Grifo Alto');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Candelarita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Desamparaditos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(4,'Chires');

--Distritos del canton de Terrazu de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(5,'San Marcos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(5,'San Lorenzo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(5,'San Carlos');

--Distritos del canton de Aserri de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Aserri');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Tarbaca');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Vuelta de Jorco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'San Gabriel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Legua');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Monterrey');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(6,'Salitrillos');

--Distritos del canton de Mora de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Colon');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Guayabo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Tabarcia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Piedras Negras');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Picagres');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Jaris');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(7,'Quitirrisi');

--Distritos del canton de Goicoechea de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Guadalupe');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'San Francisco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Calle Blancos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Mata de Platano');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Ipis');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Rancho Redondo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(8,'Purral');

--Distritos del canton de Santa Ana de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Santa Ana');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Salitral');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Pozos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Uruca');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Piedades');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(9,'Brasil');

--Distritos del canton de Alajuelita de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(10,'Alajuelita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(10,'San Josecito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(10,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(10,'Concepcion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(10,'San Felipe');

--Distritos del canton de Vasquez de Coronado de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(11,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(11,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(11,'Dulce Nombre de Jesus');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(11,'Patalillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(11,'Cascajal');

--Distritos del canton de Acosta de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(12,'San Ignacio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(12,'Guaitil');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(12,'Palmichal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(12,'Cangrejal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(12,'Sabanillas');

--Distritos del canton de Tibas de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(13,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(13,'Cinco Esquinas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(13,'Anselmo Llorente');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(13,'Leon XIII');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(13,'Colima');

--Distritos del canton de Moravia de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(14,'San Vicente');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(14,'San Jeronimo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(14,'La Trinidad');

--Distritos del canton de Montes de Oca de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(15,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(15,'Sabanilla');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(15,'Mercedes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(15,'San Rafael');

--Distritos del canton de Turrubares de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(16,'San Pablo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(16,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(16,'San Juan de Mata');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(16,'San Luis');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(16,'Carara');

--Distritos del canton de Dota de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(17,'Santa Maria');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(17,'Jardin');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(17,'Copey');

--Distritos del canton de Curridabat de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(18,'Curridabat');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(18,'Granadilla');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(18,'Sanchez');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(18,'Tirrases');

--Distritos del canton de Perez Zeledon de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'San Isidro de el General');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'El General');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Daniel Flores');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Rivas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Platanares');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Pejibaye');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Cajon');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Baru');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Rio Nuevo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'Paramo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(19,'La Amistad');

--Distritos del canton de Leon Corte Castro de la provincia de San Jose
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'San Pablo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'San Andres');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'Llano Bonito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'Santa Cruz');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(20,'San Antonio');


--Distritos del canton de Alajuela de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Alajuela');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'San Jose');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Carrizal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Guacima');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Sabanilla');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Rio Segundoo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Desamparados');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Turrucares');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Tambor');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Garita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(21,'Sarapiqui');

--Distritos del canton de San Ramon de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'San Ramon');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Santiago');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Piedades Norte');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Piedades Sur');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Los Angeles');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Alfaro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Volio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Concepcion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Zapotal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'Peñas Blancas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(22,'San Lorenzo');

--Distritos del canton de Grecia de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'Grecia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'San Jose');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'San Roque');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'Tacares');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'Puente de Piedra');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(23,'Bolivar');

--Distritos del canton de San Mateo de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(24,'San Mateo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(24,'Desmonte');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(24,'Jesus Maria');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(24,'Labrador');

--Distritos del canton de Atenas de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Atenas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Jesus');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Mercedes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Concepcion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'San Jose');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Santa Eulalia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(25,'Escobal');

--Distritos del canton de Naranjo de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'Naranjo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'San Miguel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'San Jose');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'Cirri Sur');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'San Jeronimo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'El Rosario');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(26,'Palmitos');

--Distritos del canton de Palmares de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Palmares');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Zaragoza');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Buenos Aires');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Santiago');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Candelaria');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'Esquipulas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(27,'La Granja');

--Distritos del canton de Poas de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(28,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(28,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(28,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(28,'Carrillos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(28,'Sabana Redonda');

--Distritos del canton de Orotina de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(29,'Orotina');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(29,'El Mastate');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(29,'Hacienda Vieja');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(29,'Coyolar');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(29,'La Ceiba');

--Distritos del canton de San Carlos de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Quesada');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Florencia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Buena Vista');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Aguas Zarcas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Venecia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Pital');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'La Fortuna');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'La Tigra');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'La Palmera');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Venado');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Cutis');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Moterrey');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(30,'Pocosol');

--Distritos del canton de Zarcero de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Zarcero');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Laguna');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Tapezco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Guadalupe');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Palmira');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Zapote');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(31,'Brisas');

--Distritos del canton de Sarchi de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(32,'Sarchi Norte');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(32,'Sarchi Sur');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(32,'Toro Amarillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(32,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(32,'Rodriguez');

--Distritos del canton de Upala de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Upala');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Aguas Claras');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'San Jose o Pizote');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Bijagua');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Delicias');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Dos Rios');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Yolillal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(33,'Canalete');

--Distritos del canton de Los Chiles de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(34,'Los Chiles');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(34,'Caño Negro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(34,'El Amparo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(34,'San Jorge');

--Distritos del canton de Guatuso de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(35,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(35,'Buenavista');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(35,'Cote');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(35,'Katira');

--Distritos del canton de Rio Cuarto de la provincia de Alajuela
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(36,'Rio Cuarto');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(36,'Santa Rita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(36,'Santa Isabel');

--Distritos del canton de Cartago de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Oriental');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Occidental');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Carmen');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'San Nicolas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Aguacaliente o San Francisco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Guadalupe o Arenilla');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Corralillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Dulce Nombre');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Llano Grande');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(37,'Quebradilla');

--Distritos del canton de Paraiso de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(38,'Paraiso');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(38,'Santiago');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(38,'Orosi');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(38,'Cachi');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(38,'Llanos de Santa Lucia');

--Distritos del canton de La Union de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'Tre Rios');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'San Diego');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'Concepcion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'Dulce Nombre');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'San Ramon');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(39,'Rio Azul');

--Distritos del canton de Jimenez de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(40,'Juan Viñas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(40,'Tucurrique');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(40,'Pejibaye');

--Distritos del canton de Turrialba de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Turrialba');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'La Suiza');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Peralta');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Santa Cruz');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Santa Teresita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Pavones');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Tuis');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Tayutic');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Santa Rosa');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Tres Equis');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'La Isabel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(41,'Chirripo');

--Distritos del canton de Alvarado de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(42,'Pacayas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(42,'Cervantes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(42,'Capellades');

--Distritos del canton de Oreamuno de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(43,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(43,'Cot');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(43,'Potrero Cerrado');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(43,'Cipreses');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(43,'Santa Rosa');

--Distritos del canton de El Guarco de la provincia de Cartago
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(44,'Tejar');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(44,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(44,'Tobosi');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(44,'Patio de Agua');

--Distritos del canton de Heredia de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(45,'Heredia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(45,'Mercedes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(45,'San Francisco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(45,'Ulloa');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(45,'Varablanca');

--Distritos del canton de Barva de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'Barva');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'San Pablo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'San Roque');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'Santa Lucia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(46,'San Jose de la Montaña');

--Distritos del canton de Santo Domingo de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Santo Domingo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'San Vicente');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'San Miguel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Paracito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Santo Tomas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Santa Rosa');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Tures');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(47,'Para');

--Distritos del canton de Santa Barbara de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'Santa Barbara');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'San Pedro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'Jesus');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'Santo Domingo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(48,'Puraba');

--Distritos del canton de San Rafael de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(49,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(49,'San Josecito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(49,'Santiago');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(49,'Angeles');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(49,'Concepcion');

--Distritos del canton de San Isidro de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(50,'San Isidro');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(50,'San Jose');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(50,'Concepcion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(50,'San Francisco');

--Distritos del canton de Belen de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(51,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(51,'Rivera');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(51,'La Asuncion');

--Distritos del canton de Flores de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(52,'San Joaquin');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(52,'Barrantes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(52,'Llorente');

--Distritos del canton de San Pablo de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(53,'San Pablo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(53,'Rincon de Sabanilla');

--Distritos del canton de Sarapiqui de la provincia de Heredia
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(54,'Puerto Viejo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(54,'La Virgen');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(54,'Horquetas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(54,'Llanuras del Gaspar');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(54,'Cureña');

--Distritos del canton de Liberia de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(55,'Liberia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(55,'Cañas Dulces');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(55,'Mayorga');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(55,'Nacascolo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(55,'Curubande');

--Distritos del canton de Nicoya de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Nicoya');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Mansion');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'San Antonio');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Quebrada Honda');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Samara');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Nosara');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(56,'Belen de Nosarita');

--Distritos del canton de Santa Cruz de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Santa Cruz');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Bolson');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Veitisiete de Abril');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Tempate');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Cartagena');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Cuajiniquil');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Diria');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Cabo Velas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(57,'Tamarindo');

--Distritos del canton de Bagaces de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(58,'Bagaces');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(58,'Fortuna');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(58,'Mogote');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(58,'Rio Naranjo');

--Distritos del canton de Carrillo de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(60,'Filadelfia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(60,'Palmira');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(60,'Sardinal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(60,'Belen');

--Distritos del canton de Cañas de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(61,'Cañas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(61,'Palmira');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(61,'San Miguel');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(61,'Bebedero');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(61,'Porzal');

--Distritos del canton de Abangares de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(62,'Las Juntas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(62,'Sierra');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(62,'San Juan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(62,'Colorado');

--Distritos del canton de Tilaran de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Tilaran');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Quebrada Grande');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Tronadora');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Santa Rosa');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Libano');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Tierras Morenas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(63,'Arenal');

--Distritos del canton de Nandayure de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'Carmona');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'Santa Rita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'Zapotal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'San Pablo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'Porvenir');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(64,'Bejuco');

--Distritos del canton de La Cruz de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(65,'La Cruz');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(65,'Santa Cecilia');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(65,'Garita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(65,'Santa Elena');

--Distritos del canton de Hojancha de la provincia de Guanacaste
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(66,'Hojancha');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(66,'Monte Romo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(66,'Puerto Carrillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(66,'Huacas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(66,'Matambu');

--Distritos del canton de Puntarenas de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Puntarenas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Pitahaya');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Chomes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Lepanto');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Paquera');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Manzanillo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Guacimal');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Barranca');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Monte Verde');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Isla del Coco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Cobano');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Chacarita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Chira');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Acapulco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'El Roble');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(67,'Arancibia');

--Distritos del canton de Esparza de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'Espiritu Santo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'San Juan Grande');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'Macacona');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'San Rafael');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'San Jeronimo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(68,'Caldera');

--Distritos del canton de Buenos Aires de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Buenos Aires');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Volcan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Protrero Grande');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Boruca');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Pilas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Colinas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Changena');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Briolley');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(69,'Brunka');

--Distritos del canton de Montes de Oro de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(70,'Miramar');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(70,'La Union');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(70,'San Isidro');

--Distritos del canton de Osa de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Puerto Cortes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Palmar');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Sierpe');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Bahia Ballena');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Piedras Blancas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(71,'Bahia Drake');

--Distritos del canton de Quepos de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(72,'Quepos');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(72,'Savegre');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(72,'Naranjito');

--Distritos del canton de Golfito de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(73,'Golfito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(73,'Puerto Jimenez');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(73,'Guaycara');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(73,'Pavon');

--Distritos del canton de Coto Brus de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'San Vito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'Sabalito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'Aguabuena');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'Limoncito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'Pittier');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(74,'Gutierrez Braun');

--Distritos del canton de Parrita de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(75,'Parrita');

--Distritos del canton de Corredores de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(76,'Corredor');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(76,'La Cuesta');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(76,'Canoas');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(76,'Laurel');

--Distritos del canton de Garabito de la provincia de Puntarenas
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(77,'Jaco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(77,'Tarcoles');

--Distritos del canton de Limon de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(78,'Limon');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(78,'Valle La Estrella');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(78,'Rio Blanco');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(78,'Matama');

--Distritos del canton de Pococi de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'Guapiles');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'Jimenez');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'La Rita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'Roxana');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'Cariari');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'Colorado');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(79,'La Colonia');

--Distritos del canton de Siquirres de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Siquirres');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Pacuarito');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Florida');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Germania');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Cairo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(80,'Alegria');

--Distritos del canton de Talamanca de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(81,'Bratsi');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(81,'Sixaola');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(81,'Cahuita');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(81,'Telire');

--Distritos del canton de Matina de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(82,'Matina');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(82,'Batan');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(82,'Carrandi');

--Distritos del canton de Guacimo de la provincia de Limon
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(83,'Guacimo');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(83,'Mercedes');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(83,'Pocora');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(83,'Rio Jimenez');
INSERT INTO DT_DISTRITO(CANTON_ID, NOMBRE)VALUES(83,'Duacari');
